src/answers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from products.views import (
		ProductAddView,
		ProductUpdateView,
		SellerProductListView,
        ProductAddView
	)


from .views import (
        SellerDashboard,
        SellerProductDetailRedirectView,
        SellerTransactionListView,

        )

urlpatterns = [
    url(r'^$', SellerDashboard.as_view(), name='dashboard'),
    url(r'^transactions/$', SellerTransactionListView.as_view(), name='transactions'),
    url(r'^products/$', SellerProductListView.as_view(), name='product_list'), #sellers:product_list
    # url(r'^products/(?P<pk>\d+)/$', SellerProductDetailRedirectView.as_view()),
    # url(r'^products/(?P<pk>\d+)/edit/$', ProductUpdateView.as_view(), name='product_edit'),
    url(r'^products/ask/$', ProductAddView.as_view(), name='product_create'),
]   

src/products/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from .views import ProductAddView, ProductDownloadView, ProductUpdateView, ProductDetailView, ProductListView, ExampleView, VariationListView

urlpatterns = [
    # Examples:
    #url(r'^$', 'newsletter.views.home', name='home'),
    url(r'^$', ProductListView.as_view(), name='products'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
    #url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='product_detail_slug'),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='product_inventory'),
    #url(r'^create/$', 'products.views.create_view', name='create_view'),    
    #url(r'^(?P<pk>\d+)/edit/$', 'products.views.edit_view', name='edit_view'), 
    url(r'^ask/$', ProductAddView.as_view(), name='add_view'),
    url(r'^(?P<pk>\d+)/download/$', ProductDownloadView.as_view(), name='download'),
    url(r'^(?P<slug>[\w-]+)/download/$', ProductDownloadView.as_view(), name='download_slug'), 
    url(r'^(?P<pk>\d+)/update/$', ProductUpdateView.as_view(), name='update_view'),
    url(r'^(?P<slug>[\w-]+)/update/$', ProductUpdateView.as_view(), name='update_view'), 
    # viewing an example
    url(r'^example/$', ExampleView.as_view(), name='example'),
    #url(r'^(?P<id>\d+)', 'product.views.product_detail', name='product_detail_view_func'),
]

src/products/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.core.files.storage import FileSystemStorage
from answers.models import AnswerAccount
import os
import shutil
from PIL import Image
import random
from django.core.files import File
# Create your models here.

class ProductQuerySet(models.QuerySet):
	def active(self):
		return self.filter(active=True)

class ProductManager(models.Manager):
	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db)

	def all(self, *args, **kwargs):
		return self.get_queryset().active()
       
        def get_related(self, instance):
            products_one = self.get_queryset().filter(categories__in = instance.categories.all())
            products_two = self.get_queryset().filter(default=instance.default)
            qs = (products_one | products_two).exclude(id=instance.id).distinct
            return qs #self.get_queryset()

def download_media_location(instance, filename):
    return "media/%s/%s" %(instance.slug, filename)

class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(blank=True, null=True)
	price = models.DecimalField(decimal_places=2, max_digits=1000, default=0.99)
	active = models.BooleanField(default=True)
        slug = models.SlugField(blank=True, unique=True)
        embed_code = models.CharField(max_length=500, null=True, blank=True)
        seller = models.ForeignKey(AnswerAccount, null=True, blank=True)
        media = models.FileField(blank=True, null=True, upload_to=download_media_location, storage=FileSystemStorage(location=settings.MEDIA_URL))
        categories = models.ManyToManyField('Category', blank=True)
        default = models.ForeignKey('Category', related_name='default_category', null=True, blank=True)
    
	objects = ProductManager()

        class Meta:
            ordering = ["title"]
            verbose_name = "Product"
            verbose_name_plural = "Products"

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("product_detail", kwargs={"pk": self.pk})
        def get_image_url(self):
            img = self.productimage_set.first()
            if img:
                return img.image.url
            return img #none
        def get_download(self):
           url = reverse("download_slug", kwargs={"slug": self.slug})
           return url

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug

    qs = Product.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id) 
        return create_slug(instance, new_slug=new_slug)
    return slug

def product_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_reciever, sender=Product)

def thumbnail_location(instance, filename):
    return "thumbnails/%s/%s" %(instance.product.slug, filename)
THUMB_CHOICES = (
    ("hd", "HD"),
    ("sd", "SD"),
    ("micro", "Micro"),
)

class Thumbnail(models.Model):
    product = models.ForeignKey(Product)
    type = models.CharField(max_length=20, choices=THUMB_CHOICES, default='hd')
    height = models.CharField(max_length=20, null=True, blank=True) 
    width = models.CharField(max_length=20, null=True, blank=True)
    media = models.ImageField(width_field= "width", height_field="height", blank=True, null=True, upload_to=thumbnail_location)

    def __unicode__(self):
        return str(self.media)

def create_new_thumb(media_path, instance, owner_slug, max_length, max_width):
    filename = os.path.basename(media_path)
    thumb = Image.open(media_path)
    size = (max_length, max_width)
    thumb.thumbnail(size, Image.ANTIALIAS)
    temp_loc = "%s/%s/tmp" %(settings.MEDIA_URL, owner_slug)
    if not os.path.exists(temp_loc):
        os.makedirs(temp_loc)
    temp_file_path = os.path.join(temp_loc, filename)
    if os.path.exists(temp_file_path):
        temp_path = os.path.join(temp_loc, "%s" %(random.random()))
        os.makedirs(temp_path)
        temp_file_path = os.path.join(temp_path, filename)

    temp_image = open(temp_file_path, "w")
    thumb.save(temp_image)
    thumb_data = open(temp_file_path, "r")

    thumb_file = File(thumb_data)
    instance.media.save(filename, thumb_file)
    shutil.rmtree(temp_loc, ignore_errors=True)
    return True

def product_post_save_reciever(sender, instance, created, *args, **kwargs):
    hd, hd_created = Thumbnail.objects.get_or_create(product=instance, type='hd')
    # sd, sd_created = Thumbnail.objects.get_or_create(product=instance, type='sd')
    # micro, micro_created = Thumbnail.objects.get_or_create(product=instance, type='micro')

    hd_max = (500, 500)
    sd_max = (350, 350)
    micro_max = (150, 150)

    if instance.media:
        media_path = instance.media.path
        owner_slug = instance.slug
        if hd_created:
            create_new_thumb(media_path, hd, owner_slug, hd_max[0], hd_max[1])
    
    # if sd_created:
    #     create_new_thumb(media_path, sd, owner_slug, sd_max[0], sd_max[1])

    # if micro_created:
    #     create_new_thumb(media_path, micro, owner_slug, micro_max[0], micro_max[1])

post_save.connect(product_post_save_reciever, sender=Product)

class MyProducts(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    products = models.ManyToManyField(Product, blank=True)

    def __unicode__(self):
        return "%s" %(self.products.count())
    class Meta:
        verbose_name = "My Products"
        verbose_name_plural = "My Products"


class Variation(models.Model):
    product = models.ForeignKey(Product)
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    inventory = models.IntegerField(null=True, blank=True) #unlimited amount
    price = models.DecimalField(decimal_places=2, max_digits=20, default=0.99)
    sale_price = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.title

    def get_price(self):
        if self.sale_price is not None:
            return self.sale_price
        else:
            return self.price

    def get_html_price(self):
        if self.sale_price is not None:
            html_text = "<span class='sale-price'>%s</span> <span class='og-price'>%s</span>" %(self.sale_price, self.price)
        else:
            html_text = "<span class='price'>%s</span>" %(self.price)
        return mark_safe(html_text)

    def get_absolute_url(self):
        return self.product.get_absolute_url()

    def add_to_cart(self):
        return "%s?item=%s&qty=1" %(reverse("cart"), self.id)

    def remove_from_cart(self):
        return "%s?item=%s&qty=1&delete=True" %(reverse("cart"), self.id)

    def get_title(self):
        return "%s - %s" %(self.product.title, self.title)

def product_post_saved_reciever(sender, instance, created, *args, **kwargs):
    product = instance
    variations = product.variation_set.all()
    if variations.count() == 0:
        new_var = Variation()
        new_var.product = product
        new_var.title = "Default"
        new_var.price = product.price
        new_var.save()

post_save.connect(product_post_saved_reciever, sender=Product)

def image_upload_to(instance, filename):
    title = instance.product.title
    slug = slugify(title)
    basename, file_extension = filename.split(".")
    qs = Product.objects.filter(slug=slug)
    exists = qs.exists()
    if qs:
        new_filename = "%s-%s.%s" %(slug, qs.first().id, file_extension)
    return "products/%s/%s" %(slug, new_filename)

class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to=image_upload_to)

    def __unicode__(self):
        return self.product.title

    class Meta:
        verbose_name = "Product Images"
        verbose_name_plural = "Product Images"

def image_upload_to_featured(instance, filename):
    title = instance.product.title
    slug = slugify(title)
    basename, file_extension = filename.split(".")
    qs = Product.objects.filter(slug=slug)
    exists = qs.exists()
    if qs:
        new_filename = "%s-%s.%s" %(slug, qs.first().id, file_extension)
    return "products/%s/featured/%s" %(slug, new_filename)

class ProductFeatured(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to=image_upload_to_featured)
    title = models.CharField(max_length=120, null=True, blank=True)
    text = models.CharField(max_length=220, null=True, blank=True)
    text_right = models.BooleanField(default=False)
    show_price = models.BooleanField(default=False)
    make_image_background = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Featured Product"
        verbose_name_plural = "Featured Products"

    def __unicode__(self):
        return self.product.title

# Images, Categories
class Category(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"slug": self.slug })

src/products/forms.py
from .models import Variation, Product, Category
from django import forms
from django.forms.models import modelformset_factory
from django.utils.text import slugify
from django.contrib import messages 

class VariationInventoryForm(forms.ModelForm):
	class Meta:
		model = Variation
		fields = [
		"title",
		"description",
		"price",
		"sale_price",
		"active",
		
		]
VariationInventoryFormSet = modelformset_factory(Variation, form=VariationInventoryForm, extra=0)
PUBLISH_CHOICES = (
	("publish", "Publish"),
	("draft", "Draft"), 
)
from .models import Variation, Category



class ProductFilterForm(forms.Form):
	# q = forms.CharField(label='Search', required=False)
	category_id = forms.ModelMultipleChoiceField(
		label='Category',
		queryset=Category.objects.all(), 
		widget=forms.CheckboxSelectMultiple, 
		required=False)
	
	# max_price = forms.DecimalField(decimal_places=2, max_digits=12, required=False)
	# min_price = forms.DecimalField(decimal_places=2, max_digits=12, required=False)

class CategoryForm(forms.Form):
	categories = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label=None)
	# shipping_address = forms.ModelChoiceField(queryset=UserAddress.objects.filter(type="shipping"), empty_label=None, widget=forms.RadioSelect)

class ProductModelForm(forms.ModelForm):

	class Meta:
		model = Product
		fields = [
		"title",
		"description",
		"media",
		"categories",
		]
		widgets = {
			"description": forms.Textarea(
				attrs={
					"placeholder": "Description...",
					"rows": "2"
				}
			),
			"title": forms.TextInput(
				attrs={
					"placeholder": "Question..."
				}
			),	
			"media": forms.FileInput(
				attrs={
					"class": "image"
				}

			),

			"categories": forms.CheckboxSelectMultiple(
				attrs={

				}
				
			),
		}
	def clean(self, *args, **kwargs):
		cleaned_data = super(ProductModelForm, self).clean(*args, **kwargs)
		# title = cleaned_data.get("title")
		# slug = slugify(title)
		# qs = Product.objects.filter(slug=slug).exists()
		# if qs:
		# 	raise forms.ValidationError("Unique question is required. Please submit a unique question title.")
		return cleaned_data

	def clean_title(self):
		title = self.cleaned_data.get("title")
		if len(title) > 0:
			return title
		else: 
			raise forms.ValidationError("Title must not be blank.")
	# def clean_media(self):
	# 	media = self.cleaned_data.get("media")
	# 	if media is not None:
	# 		return media
	# 	else: 
	# 		raise forms.ValidationError("Please upload a question image.")
	def clean_category(self):
		categories = self.cleaned_data.get("categories")
		if categories is not None:
			return categories
		else: 
			raise forms.ValidationError("Please select a question category.")

	# def clean_desc(self):
	# 	desc = self.cleaned_data.get("description")
	# 	if len(desc) > 3:
	# 		return desc
	# 	else: 
	# 		raise forms.ValidationError("Description must not be blank.")

src/products/templates/products/ask.html
{% extends "base.html" %}
{% block content %}
  <!-- pass context to JS as a global variable -->
  <script type="text/javascript">window.DATA = JSON.parse("{{ data.json }}".replace(/&quot;/g,"\""))</script>
    <header>
        <div class="header-content" id="ask_form">
            <div class="header-content-inner">
              <h1 style="color:white" class="form">Ask us a question</h1>
              <hr class="form">
                <div class="container-fluid">
                  <div class="row">
                    <div class="col-md-2"></div>

                    <div class="col-md-4 text-center" id="topic_group">
                      <button type="button" class="btn btn-primary dropdown-toggle form" data-toggle="dropdown" id="topic_button">
                        Choose a Topic
                      </button>
                      <ul class="dropdown-menu" role="menu" id="topic_dropdown">
                        {% for topic in data.topics %}
                          <li class="topic_list_element" id="{{ topic }}"><a>{{ topic }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>

                    <div class="col-md-4 text-center" id="concept_group">
                      <button type="button" class="btn btn-primary dropdown-toggle form" data-toggle="dropdown" id="concept_button">
                        Choose a Concept
                      </button>
                      <ul class="dropdown-menu" role="menu" id="concept_dropdown" >
                        <li><a>Please select a topic</a></li>
                      </ul>
                    </div>

                    <div class="col-md-2"></div>

                  </div> <!-- row -->

                  <br><br>

                  <div class="row">
                    <div class="col-md-2"></div>

                    <div class="col-md-4 text-center" id="title_group">
                      <input type="text" class="form-control form" id="Title" placeholder="Question Title" aria-describedby="sizing-addon1">
                    </div>

                    <div class="col-md-4 text-center" id="email_group">
                      <input type="text" class="form-control form" id="Email" placeholder="Your email address" aria-describedby="sizing-addon1">
                    </div>

                    <div class="col-md-2"></div>
                  </div> <!-- row -->

                  <br><br>

                  <div class="row">
                    <div class="col-md-12"></div>
                      <textarea class="form-control form" rows="10" id="Content"></textarea>
                    </div>
                  </div> <!-- row -->

                  <br><br>

                  <div class="row">
                    <div class="col-md-12">
                      <button type="button" class="btn btn-primary form" id="submit">
                        Submit
                      </button>
                    </div>
                  </div> <!-- row -->

                  <div class="row">
                    <div class="col-md-12" id="error">
                    </div>
                  </div>


                </div> <!-- container-fluid -->


            </div>
            <div class="header-content" id="confirm_div">
              <div class="container-fluid">
                <div class ="row">
                  <div class="col-md-2"></div>
                  <div class="col-md-8" id="confirm_header"></div
                  <div class="col-md-2"></div>
                </div>
                <div class="row">
                  <div class="col-md-4"></div>
                  <div class="col-md-4">
                    <form method="post" action="/add_example" id="confirm_form">{% csrf_token %}</form>
                  </div>
                  <div class="col-md-4"></div>
                </div>
              </div>
            </div>
        </div>
      </header>

{% endblock %}

src/products/templates/products/category_detail.html
{% extends "base.html" %}

{% block content %}

<h1 class="col-sm-offset-5">{{object}}</h1>

<div class="row">
	{% for product in products %}
<!-- {{ object_list }} returns an instance of ProductListView -->
<div class='col-xs-4'>
{% include "products/product_thumbnail.html" with product=product price="True" %}
</div>
 {% cycle '' '' '</div><div class="row">' %}

{% endfor %}
</div>
{% endblock %}

src/products/templates/products/create_view.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<header>
        <div class="header-content" id="ask_form">
            <div class="header-content-inner">
              <h1 style="color:white" class="form">Ask Questions</h1>
              <hr class="form">
                <div class="container-fluid">
                  <div class="row">
                    <div class="col-md-2"></div>

                    <div class="col-md-4 text-center" id="topic_group">
                      <button type="button" class="btn btn-primary dropdown-toggle form" data-toggle="dropdown" id="topic_button">
                        Choose a Category
                      </button>
                      <ul class="dropdown-menu" role="menu" id="topic_dropdown">
                        {% for instance in object_list %}
                          <li class="topic_list_element" id="{{ object }}"><a>{{ instance }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>

                    <div class="col-md-4 text-center" id="concept_group">
                      <button type="button" class="btn btn-primary dropdown-toggle form" data-toggle="dropdown" id="concept_button">
                        Choose a Concept
                      </button>
                      <ul class="dropdown-menu" role="menu" id="concept_dropdown" >
                        <li><a>Please select a Category</a></li>
                      </ul>
                    </div>

                <div class="row">
                    <form action="" method="POST">
        			{% csrf_token %}
        			{{ form|crispy }}
        			<button class="btn btn-primary btn-lg">Submit</button>
    				</form>
                  </div>
                </div>
              </div>
      </header>

{% endblock %}
    

src/products/templates/products/example.html
{% extends "base.html" %}
{% block content %}

<header>
  <div class="header-content" id="ask_form">
    <div class="header-content-inner">
      <h2>{{ title }}</h2>

      <iframe width="420" height="315" src="http://www.youtube.com/embed/{{ link }}?autoplay=1"></iframe>
    </div>
  </div>
</header>

{% endblock %}

src/products/templates/products/form.html
{% extends "base.html" %}
{% block content %}

{% include "products/form_include.html" with form=form submit_btn=submit_btn %}

{% endblock %}

src/products/templates/products/form_include.html
{% load crispy_forms_tags %}

<header>
        <div class="header-content" id="ask_form">
            <div class="header-content-inner">
              <h1 style="color:white" class="form">{{title}} Question</h1>
              <hr class="form">
                <div class="container-fluid">

                <div class="row">
    				<form method="POST" action="" enctype='multipart/form-data'>{% csrf_token %}{{ form|crispy }}
<input type='submit' class="btn-default btn-lg" value='{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}' /><br><br>
<input type='submit' class="btn-default btn-lg" value='{% if submit_btn2 %}{{ submit_btn2 }}{% else %}{% endif %}'/>
</form>
                  </div>
                </div>
              </div>
            </div>
      </header>

src/products/templates/products/product_detail.html
{% extends "base.html" %}

<script>
{% block jquery %}

function update_iframe_size(){
	var parent_id = $("iframe").parent().attr("id");
	if (parent_id == "main_video") {
		var parent_class = $("iframe").parent().attr("class");
		var parent_width = $("iframe").parent().width();
		console.log(parent_class);
		var width = $("iframe").css("width"); // $("iframe").width();
		var height = $("iframe").css("height");
		var ratio = parseInt(height)/parseInt(width);
		var new_height = parseInt(parent_width) * ratio
		$("iframe").css("width", parent_width);
		$("iframe").css("height", new_height);
	}
}
update_iframe_size()
$(window).bind("resize", function(){
	// alert("reized");
	update_iframe_size();
});
$('.reply_btn').click(function(e){
	e.preventDefault();
	$(this).next(".reply_comment").fadeToggle();
	// $(".reply_comment").fadeToggle();
})

function setPrice(){
	var price = $(".variation_select option:selected").attr("data-price")
	var sale_price = $(".variation_select option:selected").attr("data-sale-price")
	if (sale_price != "" && sale_price != "None" && sale_price != null ) {
	$("#price").html("<h3>" + sale_price + " <small class='og-price'>" + price  + "</small></h3>");
	} else {
	$("#price").html(price);
	}
}
setPrice()
$(".variation_select").change(function(){
	setPrice()
	// var img = $(".variation_select option:selected").attr("data-img")
	// $("img").attr("src", img);
})
$("#submit-btn").click(function(event){
	event.preventDefault();
	var formData = $("#add-form").serialize();
	console.log(formData);
	$.ajax({
		type: "GET", // "POST"
		url: "{% url 'cart' %}",
		data: formData,
		success: function(data) {
			showFlashMessage(data.flash_message);
			updateCartItemCount(); 
			
		}, 
		error: function(response, error) {
			// console.log(response)
			// console.log(error)
			$("#add-form").submit()
		}
	})
	// $("#add-form").submit()
})

{% endblock %}
</script>


{% block content %}
<div class='row'>

<div class='col-sm-8'>
<h2>{{ object.title }}</h2>

<p class='lead'>
<b> {{ object.description }} </b><br>
<br>

<div class='col-sm-12' id='main_video'>
	{% if object.embed_code %}
{{ object.embed_code|safe }}
	{% else %}
	<b>Answer Pending!</b><br>
{% endif %}


{% if object.get_image_url %}
<img id='img' class='img-responsive' src='{{ object.get_image_url }}' />
{% endif %}


{% if object.media %}
{% if request.user.is_authenticated %} 
{% if object in request.user.myproducts.products.all %}
<a href="{{ object.get_absolute_url }}update">Update</a> |
{% endif %}
<a href="{{ object.get_download }}?preview=True">Preview</a> | 
<a href="{{ object.get_download }}">Download</a>
{% endif %}
{% endif %}

{% if object.thumbnail_set.all.count > 0 %}
{% for img in object.thumbnail_set.all %}
<a href="{{ object.get_download }}?preview=True"><img src="{% if img.media %}{{ img.media.url }}{% else %}{% endif %}" class='img-responsive' /></a><br>

{% endfor %}
{% endif %}
</p>
</div>
</div>

<!-- Product Sidebar -->
<div class='col-sm-4'>

<h3 id='price'>{{ object.variation_set.first.price }}</h3>

<form id='add-form' method='GET' action="{% url 'cart' %}">
<p id='jquery-message' class='lead'>
</p>
	{% if object.variation_set.count > 1 %}
	<!-- <h3 id='price'>{{ object.variation_set.first.price }}</h3> -->

	<select name='item' class='form-control variation_select'>
		{% for vari_obj in object.variation_set.all %}
		<option  data-sale-price="{{ vari_obj.sale_price }}" data-price="{{ vari_obj.price }}" value="{{ vari_obj.id }}">{{ vari_obj }}</option>
		{% endfor %}
		</select>

	{% else %}
		<input type="hidden" name='item' value='{{ object.variation_set.first.id }}' />
			<!-- <h3 id='price'>{% if object.variation_set.first.sale_price %}
			{{ object.variation_set.first.sale_price  }}
			<small class='og-price'>{{ object.variation_set.first.price }}</small>
			{% else %}
			
			{{ object.variation_set.first.price }} -->
			{% endif %}
		</h3>


	{% endif %}
	<br/>
<input id='submit-btn' type='submit' value='Add to Cart' class='btn btn-primary' />
</form>

<br/>
<hr/>
<p>
Share<br/>
<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
<i class="fa fa-facebook-square fa-3x"></i></a>

<a href="#">
<i class="fa fa-twitter-square fa-3x"></i></a>
</p>

<hr/>
<h4>Related Answers</h4>

	<div class='row'>
	{% for product in related %}

		<div class='col-xs-6'>
			{% include "products/product_thumbnail.html" with product=product price="True" %}
		</div>
		{% cycle '' '</div><div class="row">' %}
	{% endfor %}

		</div>


</div>
<!-- End Product Sidebar -->




</div>



{% endblock %}

src/products/templates/products/product_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<br>
<br>
<br>
<br>
<div class='col-sm-2'>
<form method="GET" action="{% url 'products' %}">
{{ filter_form|crispy }}
<input type='hidden' name='q' value='{{ request.GET.q }}' />
<input type='submit' value='Apply Filter' class='btn btn-primary'>

</form>
<br>
<a class='btn btn-primary' href="{% url 'products' %}">Clear Filter</a>
</div>

<div class='col-sm-10'>

<h1>All Answers <small><a href='{% url "categories" %}'>Categories</a></small></h1>

{% if object_list.count == 0 %}

{% else %}
{% include "products/products.html" with object_list=object_list %}
{% endif %}

</div>

{% endblock %}

src/products/templates/products/product_list_snippet.html
<table>

    {% for instance in product_list %}
    <tr class="">
        <td>
            {{ instance.id }}
        </td>
        <td>
            <a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a>
        </td>
        <td>
        
<h1 class="col-sm-offset-5"><a href='{% url "categories" %}'>Categories</h1>
<div class="row">
    {% for product in object_list %}
<!-- {{ object_list }} returns an instance of ProductListView -->
<div class='col-xs-4'>
{% include "products/product_thumbnail.html" with product=product price="True"  %}
</div>
 {% cycle '' '' '</div><hr><div class="row">' %}

{% endfor %}
</div>
        </td>
   </li>
{% empty %}
    <li>No Products yet.</li>
{% endfor %}

</table>

src/products/templates/products/product_thumbnail.html
<div class="thumbnail text-center">
<h4><a href='{{ product.get_absolute_url }}'>{{ product.title }}</a></h4>
	{% if product.get_image_url %}
	<a href='{{ product.get_absolute_url }}'><img id='img' class='img-responsive' src='{{ product.get_image_url }}' /></a><br/>
	{% endif %}

	<!-- {% if price == "True" %}
		{{ product.variation_set.first.get_html_price }}
	{% endif %} -->
</div>